# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lago/proyectos/imageeditor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lago/proyectos/imageeditor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lago/proyectos/imageeditor/CMakeFiles /home/lago/proyectos/imageeditor//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lago/proyectos/imageeditor/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lago/proyectos/imageeditor/CMakeFiles /home/lago/proyectos/imageeditor//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lago/proyectos/imageeditor/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ImageEditor

# Build rule for target.
ImageEditor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ImageEditor
.PHONY : ImageEditor

# fast build rule for target.
ImageEditor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/build
.PHONY : ImageEditor/fast

lib/imgui.o: lib/imgui.cpp.o
.PHONY : lib/imgui.o

# target to build an object file
lib/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/lib/imgui.cpp.o
.PHONY : lib/imgui.cpp.o

lib/imgui.i: lib/imgui.cpp.i
.PHONY : lib/imgui.i

# target to preprocess a source file
lib/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/lib/imgui.cpp.i
.PHONY : lib/imgui.cpp.i

lib/imgui.s: lib/imgui.cpp.s
.PHONY : lib/imgui.s

# target to generate assembly for a file
lib/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/lib/imgui.cpp.s
.PHONY : lib/imgui.cpp.s

lib/imgui_demo.o: lib/imgui_demo.cpp.o
.PHONY : lib/imgui_demo.o

# target to build an object file
lib/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/lib/imgui_demo.cpp.o
.PHONY : lib/imgui_demo.cpp.o

lib/imgui_demo.i: lib/imgui_demo.cpp.i
.PHONY : lib/imgui_demo.i

# target to preprocess a source file
lib/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/lib/imgui_demo.cpp.i
.PHONY : lib/imgui_demo.cpp.i

lib/imgui_demo.s: lib/imgui_demo.cpp.s
.PHONY : lib/imgui_demo.s

# target to generate assembly for a file
lib/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/lib/imgui_demo.cpp.s
.PHONY : lib/imgui_demo.cpp.s

lib/imgui_draw.o: lib/imgui_draw.cpp.o
.PHONY : lib/imgui_draw.o

# target to build an object file
lib/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/lib/imgui_draw.cpp.o
.PHONY : lib/imgui_draw.cpp.o

lib/imgui_draw.i: lib/imgui_draw.cpp.i
.PHONY : lib/imgui_draw.i

# target to preprocess a source file
lib/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/lib/imgui_draw.cpp.i
.PHONY : lib/imgui_draw.cpp.i

lib/imgui_draw.s: lib/imgui_draw.cpp.s
.PHONY : lib/imgui_draw.s

# target to generate assembly for a file
lib/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/lib/imgui_draw.cpp.s
.PHONY : lib/imgui_draw.cpp.s

lib/imgui_impl_sdl3.o: lib/imgui_impl_sdl3.cpp.o
.PHONY : lib/imgui_impl_sdl3.o

# target to build an object file
lib/imgui_impl_sdl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/lib/imgui_impl_sdl3.cpp.o
.PHONY : lib/imgui_impl_sdl3.cpp.o

lib/imgui_impl_sdl3.i: lib/imgui_impl_sdl3.cpp.i
.PHONY : lib/imgui_impl_sdl3.i

# target to preprocess a source file
lib/imgui_impl_sdl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/lib/imgui_impl_sdl3.cpp.i
.PHONY : lib/imgui_impl_sdl3.cpp.i

lib/imgui_impl_sdl3.s: lib/imgui_impl_sdl3.cpp.s
.PHONY : lib/imgui_impl_sdl3.s

# target to generate assembly for a file
lib/imgui_impl_sdl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/lib/imgui_impl_sdl3.cpp.s
.PHONY : lib/imgui_impl_sdl3.cpp.s

lib/imgui_impl_sdlrenderer3.o: lib/imgui_impl_sdlrenderer3.cpp.o
.PHONY : lib/imgui_impl_sdlrenderer3.o

# target to build an object file
lib/imgui_impl_sdlrenderer3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/lib/imgui_impl_sdlrenderer3.cpp.o
.PHONY : lib/imgui_impl_sdlrenderer3.cpp.o

lib/imgui_impl_sdlrenderer3.i: lib/imgui_impl_sdlrenderer3.cpp.i
.PHONY : lib/imgui_impl_sdlrenderer3.i

# target to preprocess a source file
lib/imgui_impl_sdlrenderer3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/lib/imgui_impl_sdlrenderer3.cpp.i
.PHONY : lib/imgui_impl_sdlrenderer3.cpp.i

lib/imgui_impl_sdlrenderer3.s: lib/imgui_impl_sdlrenderer3.cpp.s
.PHONY : lib/imgui_impl_sdlrenderer3.s

# target to generate assembly for a file
lib/imgui_impl_sdlrenderer3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/lib/imgui_impl_sdlrenderer3.cpp.s
.PHONY : lib/imgui_impl_sdlrenderer3.cpp.s

lib/imgui_tables.o: lib/imgui_tables.cpp.o
.PHONY : lib/imgui_tables.o

# target to build an object file
lib/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/lib/imgui_tables.cpp.o
.PHONY : lib/imgui_tables.cpp.o

lib/imgui_tables.i: lib/imgui_tables.cpp.i
.PHONY : lib/imgui_tables.i

# target to preprocess a source file
lib/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/lib/imgui_tables.cpp.i
.PHONY : lib/imgui_tables.cpp.i

lib/imgui_tables.s: lib/imgui_tables.cpp.s
.PHONY : lib/imgui_tables.s

# target to generate assembly for a file
lib/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/lib/imgui_tables.cpp.s
.PHONY : lib/imgui_tables.cpp.s

lib/imgui_widgets.o: lib/imgui_widgets.cpp.o
.PHONY : lib/imgui_widgets.o

# target to build an object file
lib/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/lib/imgui_widgets.cpp.o
.PHONY : lib/imgui_widgets.cpp.o

lib/imgui_widgets.i: lib/imgui_widgets.cpp.i
.PHONY : lib/imgui_widgets.i

# target to preprocess a source file
lib/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/lib/imgui_widgets.cpp.i
.PHONY : lib/imgui_widgets.cpp.i

lib/imgui_widgets.s: lib/imgui_widgets.cpp.s
.PHONY : lib/imgui_widgets.s

# target to generate assembly for a file
lib/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/lib/imgui_widgets.cpp.s
.PHONY : lib/imgui_widgets.cpp.s

src/core/Core.o: src/core/Core.cpp.o
.PHONY : src/core/Core.o

# target to build an object file
src/core/Core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/src/core/Core.cpp.o
.PHONY : src/core/Core.cpp.o

src/core/Core.i: src/core/Core.cpp.i
.PHONY : src/core/Core.i

# target to preprocess a source file
src/core/Core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/src/core/Core.cpp.i
.PHONY : src/core/Core.cpp.i

src/core/Core.s: src/core/Core.cpp.s
.PHONY : src/core/Core.s

# target to generate assembly for a file
src/core/Core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/src/core/Core.cpp.s
.PHONY : src/core/Core.cpp.s

src/layer/Layer.o: src/layer/Layer.cpp.o
.PHONY : src/layer/Layer.o

# target to build an object file
src/layer/Layer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/src/layer/Layer.cpp.o
.PHONY : src/layer/Layer.cpp.o

src/layer/Layer.i: src/layer/Layer.cpp.i
.PHONY : src/layer/Layer.i

# target to preprocess a source file
src/layer/Layer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/src/layer/Layer.cpp.i
.PHONY : src/layer/Layer.cpp.i

src/layer/Layer.s: src/layer/Layer.cpp.s
.PHONY : src/layer/Layer.s

# target to generate assembly for a file
src/layer/Layer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/src/layer/Layer.cpp.s
.PHONY : src/layer/Layer.cpp.s

src/layer/LayerManager.o: src/layer/LayerManager.cpp.o
.PHONY : src/layer/LayerManager.o

# target to build an object file
src/layer/LayerManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/src/layer/LayerManager.cpp.o
.PHONY : src/layer/LayerManager.cpp.o

src/layer/LayerManager.i: src/layer/LayerManager.cpp.i
.PHONY : src/layer/LayerManager.i

# target to preprocess a source file
src/layer/LayerManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/src/layer/LayerManager.cpp.i
.PHONY : src/layer/LayerManager.cpp.i

src/layer/LayerManager.s: src/layer/LayerManager.cpp.s
.PHONY : src/layer/LayerManager.s

# target to generate assembly for a file
src/layer/LayerManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/src/layer/LayerManager.cpp.s
.PHONY : src/layer/LayerManager.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/node/Node.o: src/node/Node.cpp.o
.PHONY : src/node/Node.o

# target to build an object file
src/node/Node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/src/node/Node.cpp.o
.PHONY : src/node/Node.cpp.o

src/node/Node.i: src/node/Node.cpp.i
.PHONY : src/node/Node.i

# target to preprocess a source file
src/node/Node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/src/node/Node.cpp.i
.PHONY : src/node/Node.cpp.i

src/node/Node.s: src/node/Node.cpp.s
.PHONY : src/node/Node.s

# target to generate assembly for a file
src/node/Node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/src/node/Node.cpp.s
.PHONY : src/node/Node.cpp.s

src/node/NodeInput.o: src/node/NodeInput.cpp.o
.PHONY : src/node/NodeInput.o

# target to build an object file
src/node/NodeInput.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/src/node/NodeInput.cpp.o
.PHONY : src/node/NodeInput.cpp.o

src/node/NodeInput.i: src/node/NodeInput.cpp.i
.PHONY : src/node/NodeInput.i

# target to preprocess a source file
src/node/NodeInput.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/src/node/NodeInput.cpp.i
.PHONY : src/node/NodeInput.cpp.i

src/node/NodeInput.s: src/node/NodeInput.cpp.s
.PHONY : src/node/NodeInput.s

# target to generate assembly for a file
src/node/NodeInput.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/src/node/NodeInput.cpp.s
.PHONY : src/node/NodeInput.cpp.s

src/node/NodeWorkspace.o: src/node/NodeWorkspace.cpp.o
.PHONY : src/node/NodeWorkspace.o

# target to build an object file
src/node/NodeWorkspace.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/src/node/NodeWorkspace.cpp.o
.PHONY : src/node/NodeWorkspace.cpp.o

src/node/NodeWorkspace.i: src/node/NodeWorkspace.cpp.i
.PHONY : src/node/NodeWorkspace.i

# target to preprocess a source file
src/node/NodeWorkspace.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/src/node/NodeWorkspace.cpp.i
.PHONY : src/node/NodeWorkspace.cpp.i

src/node/NodeWorkspace.s: src/node/NodeWorkspace.cpp.s
.PHONY : src/node/NodeWorkspace.s

# target to generate assembly for a file
src/node/NodeWorkspace.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/src/node/NodeWorkspace.cpp.s
.PHONY : src/node/NodeWorkspace.cpp.s

src/ui/UI.o: src/ui/UI.cpp.o
.PHONY : src/ui/UI.o

# target to build an object file
src/ui/UI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/src/ui/UI.cpp.o
.PHONY : src/ui/UI.cpp.o

src/ui/UI.i: src/ui/UI.cpp.i
.PHONY : src/ui/UI.i

# target to preprocess a source file
src/ui/UI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/src/ui/UI.cpp.i
.PHONY : src/ui/UI.cpp.i

src/ui/UI.s: src/ui/UI.cpp.s
.PHONY : src/ui/UI.s

# target to generate assembly for a file
src/ui/UI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/src/ui/UI.cpp.s
.PHONY : src/ui/UI.cpp.s

src/ui/Window.o: src/ui/Window.cpp.o
.PHONY : src/ui/Window.o

# target to build an object file
src/ui/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/src/ui/Window.cpp.o
.PHONY : src/ui/Window.cpp.o

src/ui/Window.i: src/ui/Window.cpp.i
.PHONY : src/ui/Window.i

# target to preprocess a source file
src/ui/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/src/ui/Window.cpp.i
.PHONY : src/ui/Window.cpp.i

src/ui/Window.s: src/ui/Window.cpp.s
.PHONY : src/ui/Window.s

# target to generate assembly for a file
src/ui/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/src/ui/Window.cpp.s
.PHONY : src/ui/Window.cpp.s

src/ui/window/LayerWindow/LayerWindow.o: src/ui/window/LayerWindow/LayerWindow.cpp.o
.PHONY : src/ui/window/LayerWindow/LayerWindow.o

# target to build an object file
src/ui/window/LayerWindow/LayerWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/src/ui/window/LayerWindow/LayerWindow.cpp.o
.PHONY : src/ui/window/LayerWindow/LayerWindow.cpp.o

src/ui/window/LayerWindow/LayerWindow.i: src/ui/window/LayerWindow/LayerWindow.cpp.i
.PHONY : src/ui/window/LayerWindow/LayerWindow.i

# target to preprocess a source file
src/ui/window/LayerWindow/LayerWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/src/ui/window/LayerWindow/LayerWindow.cpp.i
.PHONY : src/ui/window/LayerWindow/LayerWindow.cpp.i

src/ui/window/LayerWindow/LayerWindow.s: src/ui/window/LayerWindow/LayerWindow.cpp.s
.PHONY : src/ui/window/LayerWindow/LayerWindow.s

# target to generate assembly for a file
src/ui/window/LayerWindow/LayerWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditor.dir/build.make CMakeFiles/ImageEditor.dir/src/ui/window/LayerWindow/LayerWindow.cpp.s
.PHONY : src/ui/window/LayerWindow/LayerWindow.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ImageEditor"
	@echo "... lib/imgui.o"
	@echo "... lib/imgui.i"
	@echo "... lib/imgui.s"
	@echo "... lib/imgui_demo.o"
	@echo "... lib/imgui_demo.i"
	@echo "... lib/imgui_demo.s"
	@echo "... lib/imgui_draw.o"
	@echo "... lib/imgui_draw.i"
	@echo "... lib/imgui_draw.s"
	@echo "... lib/imgui_impl_sdl3.o"
	@echo "... lib/imgui_impl_sdl3.i"
	@echo "... lib/imgui_impl_sdl3.s"
	@echo "... lib/imgui_impl_sdlrenderer3.o"
	@echo "... lib/imgui_impl_sdlrenderer3.i"
	@echo "... lib/imgui_impl_sdlrenderer3.s"
	@echo "... lib/imgui_tables.o"
	@echo "... lib/imgui_tables.i"
	@echo "... lib/imgui_tables.s"
	@echo "... lib/imgui_widgets.o"
	@echo "... lib/imgui_widgets.i"
	@echo "... lib/imgui_widgets.s"
	@echo "... src/core/Core.o"
	@echo "... src/core/Core.i"
	@echo "... src/core/Core.s"
	@echo "... src/layer/Layer.o"
	@echo "... src/layer/Layer.i"
	@echo "... src/layer/Layer.s"
	@echo "... src/layer/LayerManager.o"
	@echo "... src/layer/LayerManager.i"
	@echo "... src/layer/LayerManager.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/node/Node.o"
	@echo "... src/node/Node.i"
	@echo "... src/node/Node.s"
	@echo "... src/node/NodeInput.o"
	@echo "... src/node/NodeInput.i"
	@echo "... src/node/NodeInput.s"
	@echo "... src/node/NodeWorkspace.o"
	@echo "... src/node/NodeWorkspace.i"
	@echo "... src/node/NodeWorkspace.s"
	@echo "... src/ui/UI.o"
	@echo "... src/ui/UI.i"
	@echo "... src/ui/UI.s"
	@echo "... src/ui/Window.o"
	@echo "... src/ui/Window.i"
	@echo "... src/ui/Window.s"
	@echo "... src/ui/window/LayerWindow/LayerWindow.o"
	@echo "... src/ui/window/LayerWindow/LayerWindow.i"
	@echo "... src/ui/window/LayerWindow/LayerWindow.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

